### ISSUE TITLE
[MMBNLC] Could not encode character with french accents

### ISSUE THREAD

**Issue by Schneitizel** [Prof9/TextPet#4]
Hi, thanks for your software!
I have some problems when reinserting; if two special characters (For example éé in the sentence "On créé" (We create)), the reinsertion fails and gives me the error : 

"FATAL: Could not encode character  in script 0 of text archive 70BD8C."

The character is missing in the log, so I guess it tries to get a character that never existed
Even adding é or éé in the bn-1-utf8.tbl, the problem occurs
This does it even with àà

Any idea how to fix this?
Thanks!

![image](https://user-images.githubusercontent.com/24242526/233771912-32c222d7-7952-447d-b155-fb65113c6a60.png)
![image](https://user-images.githubusercontent.com/24242526/233771935-e0149c0c-d089-4883-bf16-2c6f3dd4a4c0.png)

**Comment by Prof9** [comment]
Please read the relevant guide: https://forums.therockmanexezone.com/mmbnlc-modifying-adding-new-characters-to-the-font-t16728.html
