### ISSUE TITLE
[MMBNLC] MMBN3 fails to extract.

### ISSUE THREAD

**Issue by 7743onakaippai** [Prof9/TextPet#5]
![exe3](https://user-images.githubusercontent.com/131172172/236611226-c9cea174-a49c-439a-9f19-d424383192cc.png)

**Command**
`TextPet.exe Load-Plugins plugins Game MMBN3-LC Read-Text-Archives message_jap_msg --format msg Write-Text-Archives message_jap.tpl --single --format tpl Write-Text-Archives message_jap_tpl --format tpl`

**Comment by Prof9** [comment]
Looks like I made an error in `games.ini`. For EXE3/MMBN3, there is no separate command database for AC/LC.

Can you try making the change to `games.ini` in https://github.com/Prof9/TextPet/commit/3088b0bac511465750e38253b64821095eb8f63a locally and see if it works now? Also, the game ID should be `EXE3-LC`.

**Comment by 7743onakaippai** [comment]
We confirmed that both the English version (MMBN3-LC) and the Japanese version (EXE3-AC) worked properly.
Thank you very much.
