### ISSUE TITLE
[MMBNLC]Japanese text in MMBN1,2,4,5 is garbled.

### ISSUE THREAD

**Issue by 7743onakaippai** [Prof9/TextPet#6]
I have extracted the Japanese msg file to tpl format, but the Japanese messages in the script seem to be garbled.
MMBN3 is unconfirmed due to #5 issue.
MMBN6 was able to ectract to read.

**Commands**
`TextPet.exe Load-Plugins plugins Game [GameID] Read-Text-Archives message_jap_msg --format msg Write-Text-Archives message_jap.tpl --single --format tpl Write-Text-Archives message_jap_tpl --format tpl`

**I put it in [GameID].**
```
MMBN1-LC
MMBN2-LC
MMBN4-LC
MMBN5-LC
```
MMBN1
![exe1](https://user-images.githubusercontent.com/131172172/236611768-fda8db3b-009a-401a-8a9f-f0bee39815c6.png)
MMBN2
![exe2](https://user-images.githubusercontent.com/131172172/236611771-8a26b780-0642-42c2-a6d4-7c5abe62a418.png)
MMBN4
![exe4](https://user-images.githubusercontent.com/131172172/236611774-f1f7ff4a-89c0-4b81-90f2-dc8281752f8f.png)
MMBN5
![exe5](https://user-images.githubusercontent.com/131172172/236611775-f5177ce1-ac2f-4325-9389-e5fff0e3e710.png)

**Comment by Prof9** [comment]
Correct game IDs for Japanese version are: `EXE1-AC`, `EXE2-AC`, `EXE4-AC`, `EXE5-AC`.
